export const FETCH_ALL_CATEGORIES_START = 'FETCH_ALL_CATEGORIES_START'
export const FETCH_ALL_CATEGORIES_SUCCESS = 'FETCH_ALL_CATEGORIES_SUCCESS'
export const FETCH_ALL_CATEGORIES_FAILED = 'FETCH_ALL_CATEGORIES_FAILED'

export const FETCH_RECEIPT_BY_CATEGORY_START = 'FETCH_RECEIPT_BY_CATEGORY_START'
export const FETCH_RECEIPT_BY_CATEGORY_SUCCESS = 'FETCH_RECEIPT_BY_CATEGORY_SUCCESS'
export const FETCH_RECEIPT_BY_CATEGORY_FAILED = 'FETCH_RECEIPT_BY_CATEGORY_FAILED'


export const USER_AUTHENTICATION_START = 'USER_AUTHENTICATION_START'
export const USER_AUTHENTICATION_SUCCESS = 'USER_AUTHENTICATION_SUCCESS'
export const USER_AUTHENTICATION_FAILED = 'USER_AUTHENTICATION_FAILED'

export const USER_LOGOUT = 'USER_LOGOUT'